---
name: Check issue dependencies
on:
  issues:
    types:
      - opened
      - reopened
      - edited

jobs:
  check_dependencies:
    runs-on: ubuntu-latest
    name: Check Dependencies
    permissions:
      issues: read # Reason: To check issues for dependencies.
    steps:
    - uses: gregsdennis/dependencies-action@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
